# Autogenerated wrapper script for MMG_jll for armv6l-linux-musleabihf
export libmmg, libmmg2d, libmmg3d, libmmgs, mmg2d_O3, mmg3d_O3, mmgs_O3

using LinearElasticity_jll
using SCOTCH_jll
JLLWrappers.@generate_wrapper_header("MMG")
JLLWrappers.@declare_library_product(libmmg, "libmmg.so.5")
JLLWrappers.@declare_library_product(libmmg2d, "libmmg2d.so.5")
JLLWrappers.@declare_library_product(libmmg3d, "libmmg3d.so.5")
JLLWrappers.@declare_library_product(libmmgs, "libmmgs.so.5")
JLLWrappers.@declare_executable_product(mmg2d_O3)
JLLWrappers.@declare_executable_product(mmg3d_O3)
JLLWrappers.@declare_executable_product(mmgs_O3)
function __init__()
    JLLWrappers.@generate_init_header(LinearElasticity_jll, SCOTCH_jll)
    JLLWrappers.@init_library_product(
        libmmg,
        "lib/libmmg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmg2d,
        "lib/libmmg2d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmg3d,
        "lib/libmmg3d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmgs,
        "lib/libmmgs.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mmg2d_O3,
        "bin/mmg2d_O3",
    )

    JLLWrappers.@init_executable_product(
        mmg3d_O3,
        "bin/mmg3d_O3",
    )

    JLLWrappers.@init_executable_product(
        mmgs_O3,
        "bin/mmgs_O3",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
