# Autogenerated wrapper script for MMG_jll for i686-w64-mingw32
export libmmg, libmmg2d, libmmg3d, libmmgs, mmg2d_O3, mmg3d_O3, mmgs_O3

using LinearElasticity_jll
JLLWrappers.@generate_wrapper_header("MMG")
JLLWrappers.@declare_library_product(libmmg, "libmmg.dll")
JLLWrappers.@declare_library_product(libmmg2d, "libmmg2d.dll")
JLLWrappers.@declare_library_product(libmmg3d, "libmmg3d.dll")
JLLWrappers.@declare_library_product(libmmgs, "libmmgs.dll")
JLLWrappers.@declare_executable_product(mmg2d_O3)
JLLWrappers.@declare_executable_product(mmg3d_O3)
JLLWrappers.@declare_executable_product(mmgs_O3)
function __init__()
    JLLWrappers.@generate_init_header(LinearElasticity_jll)
    JLLWrappers.@init_library_product(
        libmmg,
        "bin\\libmmg.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmg2d,
        "bin\\libmmg2d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmg3d,
        "bin\\libmmg3d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmgs,
        "bin\\libmmgs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mmg2d_O3,
        "bin\\mmg2d_O3.exe",
    )

    JLLWrappers.@init_executable_product(
        mmg3d_O3,
        "bin\\mmg3d_O3.exe",
    )

    JLLWrappers.@init_executable_product(
        mmgs_O3,
        "bin\\mmgs_O3.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
