# Autogenerated wrapper script for MMG_jll for x86_64-apple-darwin
export libmmg, libmmg2d, libmmg3d, libmmgs, mmg2d_O3, mmg3d_O3, mmgs_O3

using LinearElasticity_jll
using SCOTCH_jll
JLLWrappers.@generate_wrapper_header("MMG")
JLLWrappers.@declare_library_product(libmmg, "@rpath/libmmg.5.dylib")
JLLWrappers.@declare_library_product(libmmg2d, "@rpath/libmmg2d.5.dylib")
JLLWrappers.@declare_library_product(libmmg3d, "@rpath/libmmg3d.5.dylib")
JLLWrappers.@declare_library_product(libmmgs, "@rpath/libmmgs.5.dylib")
JLLWrappers.@declare_executable_product(mmg2d_O3)
JLLWrappers.@declare_executable_product(mmg3d_O3)
JLLWrappers.@declare_executable_product(mmgs_O3)
function __init__()
    JLLWrappers.@generate_init_header(LinearElasticity_jll, SCOTCH_jll)
    JLLWrappers.@init_library_product(
        libmmg,
        "lib/libmmg.5.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmg2d,
        "lib/libmmg2d.5.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmg3d,
        "lib/libmmg3d.5.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmmgs,
        "lib/libmmgs.5.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mmg2d_O3,
        "bin/mmg2d_O3",
    )

    JLLWrappers.@init_executable_product(
        mmg3d_O3,
        "bin/mmg3d_O3",
    )

    JLLWrappers.@init_executable_product(
        mmgs_O3,
        "bin/mmgs_O3",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
